// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8dyLLIPuS-qGzeEjG_Zq_B41_6QbVfDw',
    appId: '1:401481256475:web:73e3e07711c78a0fc7b2be',
    messagingSenderId: '401481256475',
    projectId: 'edu-vista-71bae',
    authDomain: 'edu-vista-71bae.firebaseapp.com',
    storageBucket: 'edu-vista-71bae.appspot.com',
    measurementId: 'G-109HMHWNHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNmPpVs_VkCUESacO5yrJ13rWm3VxKYjY',
    appId: '1:401481256475:android:e4bbbc84286f5addc7b2be',
    messagingSenderId: '401481256475',
    projectId: 'edu-vista-71bae',
    storageBucket: 'edu-vista-71bae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIrJpmh_Hz2tkhmkw7b_PQwSh4ieRhIAw',
    appId: '1:401481256475:ios:7ea85f76892d4c9ec7b2be',
    messagingSenderId: '401481256475',
    projectId: 'edu-vista-71bae',
    storageBucket: 'edu-vista-71bae.appspot.com',
    iosBundleId: 'com.example.eduVistaApp',
  );
}
